import assert from 'node:assert/strict'
import test from 'node:test'
import { CommandRegistry } from '../src/core/registry.js'
import { registerBuiltInCommands } from '../src/plugins/index.js'

test('enregistre un catalogue étendu de commandes françaises sans anciens noms anglais', () => {
  const registry = new CommandRegistry()
  registerBuiltInCommands(registry)
  assert.ok(registry.list().length >= 160)
  for (const oldName of ['ping', 'uptime', 'owner', 'kick', 'add', 'open', 'close', 'warn', 'sticker']) {
    assert.equal(registry.get(oldName), undefined, oldName)
  }
  for (const frenchName of [
    'latence',
    'duree',
    'proprietaire',
    'expulser',
    'ajouter',
    'ouvrir',
    'fermer',
    'avertir',
    'calculer',
    'reglement',
    'messagesdisparition',
    'filigrane',
    'ticket',
    'catalogue',
    'etatserveur',
    'assistant',
    'convertiraudio',
    'vocal',
    'voix',
    'creerpdf',
    'budget',
    'morpion',
    'photoprofil',
    'lirestatuts',
    'autostatuts',
    'presence',
    'apropos',
    'confidentialite',
    'duo',
    'taghid',
    'telecharger',
    'telechargeraudio',
    'qualites',
    'vitesse',
    'muetvideo',
    'capturevideo',
    'commande',
    'genererimage',
    'modifierimage',
    'generervideo',
    'animerimage',
    'modifiervideo',
    'serviceclientia',
    'produitsdigitaux',
    'acheterdigital',
    'produitdigital',
    'livrerdigital',
    '3d',
    'angel',
    'avenger',
    'blub',
    'bpink',
    'cat',
    'glitch',
    'glitter',
    'graffiti',
    'hacker',
    'light',
    'marvel',
    'neon',
    'sci',
    'sign',
    'tattoo',
    'watercolor',
    'fullpp',
    'gjid',
    'jid',
    'left',
    'call',
    'caption',
    'clear',
    'contacts',
    'delete',
    'dlt',
    'doc',
    'online',
    'poll',
    'read',
    'scstatus',
    'setstatus',
    'status',
    'vv',
  ]) {
    assert.ok(registry.get(frenchName), frenchName)
  }
  for (const alias of ['block', 'unblock', 'pp']) assert.ok(registry.get(alias), alias)
})
